version: '3.8'

services:
  server:
    build: .
    container_name: server-node-prod
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    networks:
      - server-db
    restart: unless-stopped

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-db
    restart: unless-stopped

volumes:
  db-data:

networks:
  server-db:
    driver: bridge
